{
    "_Type": "Action.Type.ApplicationUpdate",
    "ActionResult": {
        "_Name": "Appupdate"
    },
    "OnFailure": "/CreateClaims/Actions/UpdateFailureMessage.action",
    "OnSuccess": "/CreateClaims/Actions/UpdateSuccessMessage.action"
}