{
    "CreateLinks": [],
    "OnFailure": "/CreateClaims/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/CreateClaims/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "ClaimDate": "#Control:ClaimDate/#Value",
        "Provider": "#Control:Provider/#Value",
        "Amount": "#Control:Amount/#Value",
        "Comment": "#Control:Comment/#Value",
        "claimType_ID": "#Control:claimType_ID/#SelectedValue"
    },
    "Target": {
        "EntitySet": "Claims",
        "Service": "/CreateClaims/Services/service1.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}